sudo: false
language: bash
before_script:
  - echo '-j2' > "$HOME/.proverc"
script:
  - make test TEST_ARGS=--verbose-log
after_failure:
  - make test-results
notifications:
  email:
    on_success: change
    on_failure: always
