#!/bin/sh

# This program is licensed under the GNU GPL version 2 or later.
# (c) Richard "RichiH" Hartmann <richih@debian.org>, 2011-2015
# For details, see LICENSE. To submit patches, you have to agree to
# license your code under the GNU GPL version 2 or later.

# While the following is not legally binding, the author would like to
# explain the choice of GPLv2+ over GPLv3+.
# The author prefers GPLv3+ over GPLv2+ but feels it's better to maintain
# full compatibility's with Git. In case Git ever changes its licensing terms,
# which is admittedly extremely unlikely to the point of being impossible,
# this software will most likely follow suit.

# This should always be the first line of code to facilitate debugging
[ -n "$VCSH_DEBUG" ] && set -vx

. "$(dirname "$0")/vcsh-functions"

# If '.git-HEAD' is appended to the version, you are seeing an unreleased
# version of vcsh; the master branch is supposed to be clean at all times
# so you can most likely just use it nonetheless
VERSION='1.20141026'
SELF=$(basename $0)

# We need to run getops as soon as possible so we catch -d and other
# options that will modify our behaviour.
# Commands are handled at the end of this script.
while getopts "c:dv" flag; do
	if [ x"$1" = x'-d' ] || [ x"$1" = x'--debug' ]; then
		set -vx
		VCSH_DEBUG=1
		echo "debug mode on"
		echo "$SELF $VERSION"
	elif [ x"$1" = x'-v' ]; then
		VCSH_VERBOSE=1
		echo "verbose mode on"
		echo "$SELF $VERSION"
	elif [ x"$1" = x'-c' ]; then
		VCSH_OPTION_CONFIG=$OPTARG
	fi
	shift 1
done
[ -n "$VCSH_DEBUG" ]                  && set -vx

# Read configuration and set defaults if anything's not set
: ${XDG_CONFIG_HOME:="$HOME/.config"}
source_configs
[ -n "$VCSH_DEBUG" ]                  && set -vx

set_defaults
validate_env_options

debug $(git version)

VCSH_COMMAND=$(expand_abbrev_cmd "$1"); export VCSH_COMMAND

# First handle commands which exit immediately
if [ x"$VCSH_COMMAND" = x'version' ]; then
	echo "$SELF $VERSION"
	git version
	exit
fi
if [ -z "$VCSH_COMMAND" ] || [ x"$VCSH_COMMAND" = x'help' ]; then
	# $1 is empty, or 'help'
	help && exit
fi

if [ x"$VCSH_COMMAND" = x'clone' ]; then
	parse_clone_args "$@"
elif [ x"$VCSH_COMMAND" = x'which' ]; then
	parse_which_args "$@"
	shift 1
elif [ x"$VCSH_COMMAND" = x'delete' ]           ||
     [ x"$VCSH_COMMAND" = x'enter' ]            ||
     [ x"$VCSH_COMMAND" = x'init' ]             ||
     [ x"$VCSH_COMMAND" = x'list-tracked-by' ]  ||
     [ x"$VCSH_COMMAND" = x'upgrade' ]          ||
     [ x"$VCSH_COMMAND" = x'write-gitignore' ]; then
	parse_repo_args "$@"
elif [ x"$VCSH_COMMAND" = x'rename' ]; then
	parse_rename_args "$@"
elif [ x"$VCSH_COMMAND" = x'run' ]; then
	parse_run_args "$@"
	shift 2
elif [ x"$VCSH_COMMAND" = x'foreach' ]; then
	[ -z "$2" ] && fatal "$VCSH_COMMAND: please specify a command" 1
	shift 1
elif [ x"$VCSH_COMMAND" = x'commit' ] ||
     [ x"$VCSH_COMMAND" = x'list'   ] ||
     [ x"$VCSH_COMMAND" = x'list-tracked' ] ||
     [ x"$VCSH_COMMAND" = x'list-untracked' ] ||
     [ x"$VCSH_COMMAND" = x'pull'   ] ||
     [ x"$VCSH_COMMAND" = x'push'   ]; then
	:
elif [ x"$VCSH_COMMAND" = x'status' ]; then
	parse_status_args "$@"
elif [ -n "$2" ]; then
	VCSH_COMMAND='run'; export VCSH_COMMAND
	parse_implicit_args "$@"
	shift 1
	set -- "git" "$@"
else
	VCSH_COMMAND='enter'; export VCSH_COMMAND
	parse_implicit_args "$@"
fi

# Did we receive a directory instead of a name?
# Mangle the input to fit normal operation.
if echo "$VCSH_REPO_NAME" | grep -q '/'; then
	enter_repo "$(basename "$VCSH_REPO_NAME" .git)" "$VCSH_REPO_NAME"
fi

check_needed_dirs

VCSH_COMMAND=$(echo "$VCSH_COMMAND" | sed 's/-/_/g'); export VCSH_COMMAND

run_vcsh_cmd "$VCSH_COMMAND" "$@"
